name: get-event-name
# pull_requestイベントは、デフォルトではPRの作成、reopen、PRのブランチの更新で実行される
on:
  push:
  pull_request:
  issue_comment:
jobs:
  get-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
