name: get-pr-number
on: pull_request
jobs:
  get_pull_request_number:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo $GITHUB_REF
          PR_NUMBER=$(echo $GITHUB_REF | cut -d '/' -f 3)
          echo $PR_NUMBER
  use_environment_variables:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | cut -d '/' -f 3)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      - run: echo $PR_NUMBER
      - run: echo ${{ env.PR_NUMBER }}
