name: learn-sharing-data-between-jobs
on: [push]
jobs:
  output:
    runs-on: ubuntu-20.04
    steps:
      - run: expr 1 + 1 > output.log
      - run: ls -l
  use-output:
    runs-on: ubuntu-20.04
    needs: output
    steps:
      - run: ls -l
  upload-file:
    runs-on: ubuntu-20.04
    steps:
      - run: expr 1 + 1 > output.log
      - uses: actions/upload-artifact@v3
        with:
          name: output-log
          path: output.log
  download-file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output-log
      - run: cat output-log
