on:
  push:
    paths:
      - nodejs-prisma-example/**/*
      - .github/workflows/mysql-service-container.yml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejs-prisma-example
    services:
      mysql:
        image: mysql:8.0.31-debian
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: secret
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn
          yarn run prisma migrate dev
          yarn run test
        env:
          DATABASE_URL: mysql://root:secret@localhost:3306/playground
