on:
  push:
    paths:
      - nodejs-prisma-example/**/*
      - .github/workflows/mysq-service-container.yml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejs-prisma-example
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: echo 'job succeeded!'
